server:
  port: 8080

spring:
  application:
    name: metahub
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.metahub: INFO
    org.springframework: WARN
    org.hibernate: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

